### PR TITLE
fix(openai-compatible-builder): ignore embed & gemini-2.5-pro model

### LINKED ISSUE #649: Google Gemini API key keeps failing health check
### Describe the bug

During the initial onboarding screen where the users are asked to choose their AI provider of their choice, I am unable to choose Google Gemini even with a valid API key. The health checks keep failing as it attempts to perform it on a model named `embedding-gecko-001` which seems outdated and does not exist in the Gemini model suite anymore. Even if it does, by the looks of it, the code expects an output back as text which I don't think the embedding models are capable of providing. Ideally the user should be able to choose the model provider as well as the model of their choice, and then the health check is to be performed. Models available and providers list's maintenance can probably be outsourced to an external 3rd party library as well

### System Info

```Shell
I tried it out on the hosted website, I haven't setup the repo locally yet
```

### Validations

- [x] Follow our [Code of Conduct](https://github.com/moeru-ai/airi/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guide](https://github.com/moeru-ai/airi/blob/main/.github/CONTRIBUTING.md).
- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [x] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

### PR DESCRIPTION
**Pull request by kwaa**
fix #649 

image

### CODE REVIEW

File: packages/stage-ui/src/stores/providers/openai-compatible-builder.ts [hunk 1]
```diff
@@ -122,7 +122,17 @@ export function buildOpenAICompatibleProvider(
             Authorization: `Bearer ${apiKey}`,
           },
         })
-        if (models && models.length > 0)
+          .then(models => models.filter(model =>
+            [
+              // exclude embedding models
+              'embed',
```
Comment (nekomeowww) [inline packages/stage-ui/src/stores/providers/openai-compatible-builder.ts:128]:
```suggestion
              // exclude embedding models
              'embed',
              // exclude tts models, specifically for OpenAI
              'tts',
```
