### PR TITLE
fix(stage-ui,stage-ui-three): resolve tamagotchi VRM loading screen hang on startup

### LINKED ISSUE #893: bug: cannot load VRM into scene after refresh & booted
### Describe the bug

Image

Image

```
TresCanvas: The canvas has no area, so nothing can be rendered. Set it manually on the parent element or use the prop windowSize.
(anonymous) @ rrweb-plugin-console-record.js:160
(anonymous) @ tres-BbeJkuKI.js?v=4973b764:3025
animation.ts:47 createVRMAnimationClip: VRMLookAtQuaternionProxy is not found. Creating a new one automatically. To suppress this warning, create a VRMLookAtQuaternionProxy manually
(anonymous) @ rrweb-plugin-console-record.js:160
createVRMAnimationClip @ @pixiv_three-vrm-animation.js?v=4973b764:1531
clipFromVRMAnimation @ animation.ts:47
loadModel @ VRMModel.vue:330
VRMModel.vue:340 THREE.PropertyBinding: No target node found for track: Normalized_J_Bip_C_Hips.position.
(anonymous) @ rrweb-plugin-console-record.js:160
warn @ three.module-fIQxiQPx.js?v=4973b764:1593
bind @ three.module-fIQxiQPx.js?v=4973b764:35619
_getValue_unbound @ three.module-fIQxiQPx.js?v=4973b764:35596
saveOriginalState @ three.module-fIQxiQPx.js?v=4973b764:35311
_activateAction @ three.module-fIQxiQPx.js?v=4973b764:36607
play @ three.module-fIQxiQPx.js?v=4973b764:36100
loadModel @ VRMModel.vue:340
VRMModel.vue:340 THREE.PropertyBinding: No target node found for track: Normalized_J_Bip_C_Hips.quaternion.
(anonymous) @ rrweb-plugin-console-record.js:160
warn @ three.module-fIQxiQPx.js?v=4973b764:1593
bind @ three.module-fIQxiQPx.js?v=4973b764:35619
_getValue_unbound @ three.module-fIQxiQPx.js?v=4973b764:35596
saveOriginalState @ three.module-fIQxiQPx.js?v=4973b764:35311
_activateAction @ three.module-fIQxiQPx.js?v=4973b764:36607
play @ three.module-fIQxiQPx.js?v=4973b764:36100
loadModel @ VRMModel.vue:340
VRMModel.vue:340 THREE.PropertyBinding: No target node found for track: Normalized_J_Bip_C_Spine.quaternion.
(anonymous) @ rrweb-plugin-console-record.js:160
warn @ three.module-fIQxiQPx.js?v=4973b764:1593
bind @ three.module-fIQxiQPx.js?v=4973b764:35619
_getValue_unbound @ three.module-fIQxiQPx.js?v=4973b764:35596
saveOriginalState @ three.module-fIQxiQPx.js?v=4973b764:35311
_activateAction @ three.module-fIQxiQPx.js?v=4973b764:36607
play @ three.module-fIQxiQPx.js?v=4973b764:36100
loadModel @ VRMModel.vue:340
VRMModel.vue:340 THREE.PropertyBinding: No target node found for track: Normalized_J_Bip_C_Chest.quaternion.
(anonymous) @ rrweb-plugin-console-record.js:160
warn @ three.module-fIQxiQPx.js?v=4973b764:1593
bind @ three.module-fIQxiQPx.js?v=4973b764:35619
_getValue_unbound @ three.module-fIQxiQPx.js?v=4973b764:35596
saveOriginalState @ three.module-fIQxiQPx.js?v=4973b764:35311
_activateAction @ three.module-fIQxiQPx.js?v=4973b764:36607
play @ three.module-fIQxiQPx.js?v=4973b764:36100
loadModel @ VRMModel.vue:340
VRMModel.vue:340 THREE.PropertyBinding: No target node found for track: Normalized_J_Bip_C_UpperChest.quaternion.
(anonymous) @ rrweb-plugin-console-record.js:160
warn @ three.module-fIQxiQPx.js?v=4973b764:1593
bind @ three.module-fIQxiQPx.js?v=4973b764:35619
_getValue_unbound @ three.module-fIQxiQPx.js?v=4973b764:35596
saveOriginalState @ three.module-fIQxiQPx.js?v=4973b764:35311
_activateAction @ three.module-fIQxiQPx.js?v=4973b764:36607
play @ three.module-fIQxiQPx.js?v=4973b764:36100
loadModel @ VRMModel.vue:340
VRMModel.vue:340 THREE.PropertyBinding: No target node found for track: Normalized_J_Bip_C_Neck.quaternion.
(anonymous) @ rrweb-plugin-console-record.js:160
warn @ three.module-fIQxiQPx.js?v=4973b764:1593
bind @ three.module-fIQxiQPx.js?v=4973b764:35619
_getValue_unbound @ three.module-fIQxiQPx.js?v=4973b764:35596
saveOriginalState @ three.module-fIQxiQPx.js?v=4973b764:35311
_activateAction @ three.module-fIQxiQPx.js?v=4973b764:36607
play @ three.module-fIQxiQPx.js?v=4973b764:36100
loadModel @ VRMModel.vue:340
VRMModel.vue:340 THREE.PropertyBinding: No target node found for track: Normalized_J_Bip_L_Shoulder.quaternion.
(anonymous) @ rrweb-plugin-console-record.js:160
warn @ three.module-fIQxiQPx.js?v=4973b764:1593
bind @ three.module-fIQxiQPx.js?v=4973b764:35619
_getValue_unbound @ three.module-fIQxiQPx.js?v=4973b764:35596
saveOriginalState @ three.module-fIQxiQPx.js?v=4973b764:35311
_activateAction @ three.module-fIQxiQPx.js?v=4973b764:36607
play @ three.module-fIQxiQPx.js?v=4973b764:36100
loadModel @ VRMModel.vue:340
VRMModel.vue:340 THREE.PropertyBinding: No target node found for track: Normalized_J_Bip_L_UpperArm.quaternion.
(anonymous) @ rrweb-plugin-console-record.js:160
warn @ three.module-fIQxiQPx.js?v=4973b764:1593
bind @ three.module-fIQxiQPx.js?v=4973b764:35619
_getValue_unbound @ three.module-fIQxiQPx.js?v=4973b764:35596
saveOriginalState @ three.module-fIQxiQPx.js?v=4973b764:35311
_activateAction @ three.module-fIQxiQPx.js?v=4973b764:36607
play @ three.module-fIQxiQPx.js?v=4973b764:36100
loadModel @ VRMModel.vue:340
VRMModel.vue:340 THREE.PropertyBinding: No target node found for track: Normalized_J_Bip_L_LowerArm.quaternion.
(anonymous) @ rrweb-plugin-console-record.js:160
warn @ three.module-fIQxiQPx.js?v=4973b764:1593
bind @ three.module-fIQxiQPx.js?v=4973b764:35619
_getValue_unbound @ three.module-fIQxiQPx.js?v=4973b764:35596
saveOriginalState @ three.module-fIQxiQPx.js?v=4973b764:35311
_activateAction @ three.module-fIQxiQPx.js?v=4973b764:36607
play @ three.module-fIQxiQPx.js?v=4973b764:36100
loadModel @ VRMModel.vue:340
VRMModel.vue:340 THREE.PropertyBinding: No target node found for track: Normalized_J_Bip_L_Hand.quaternion.
(anonymous) @ rrweb-plugin-console-record.js:160
warn @ three.module-fIQxiQPx.js?v=4973b764:1593
bind @ three.module-fIQxiQPx.js?v=4973b764:35619
_getValue_unbound @ three.module-fIQxiQPx.js?v=4973b764:35596
saveOriginalState @ three.module-fIQxiQPx.js?v=4973b764:35311
_activateAction @ three.module-fIQxiQPx.js?v=4973b764:36607
play @ three.module-fIQxiQPx.js?v=4973b764:36100
loadModel @ VRMModel.vue:340
VRMModel.vue:340 THREE.PropertyBinding: No target node found for track: Normalized_J_Bip_R_Shoulder.quaternion.
(anonymous) @ rrweb-plugin-console-record.js:160
warn @ three.module-fIQxiQPx.js?v=4973b764:1593
bind @ three.module-fIQxiQPx.js?v=4973b764:35619
_getValue_unbound @ three.module-fIQxiQPx.js?v=4973b764:35596
saveOriginalState @ three.module-fIQxiQPx.js?v=4973b764:35311
_activateAction @ three.module-fIQxiQPx.js?v=4973b764:36607
play @ three.module-fIQxiQPx.js?v=4973b764:36100
loadModel @ VRMModel.vue:340
VRMModel.vue:340 THREE.PropertyBinding: No target node found for track: Normalized_J_Bip_R_UpperArm.quaternion.
(anonymous) @ rrweb-plugin-console-record.js:160
warn @ three.module-fIQxiQPx.js?v=4973b764:1593
bind @ three.module-fIQxiQPx.js?v=4973b764:35619
_getValue_unbound @ three.module-fIQxiQPx.js?v=4973b764:35596
saveOriginalState @ three.module-fIQxiQPx.js?v=4973b764:35311
_activateAction @ three.module-fIQxiQPx.js?v=4973b764:36607
play @ three.module-fIQxiQPx.js?v=4973b764:36100
loadModel @ VRMModel.vue:340
VRMModel.vue:340 THREE.PropertyBinding: No target node found for track: Normalized_J_Bip_R_LowerArm.quaternion.
(anonymous) @ rrweb-plugin-console-record.js:160
warn @ three.module-fIQxiQPx.js?v=4973b764:1593
bind @ three.module-fIQxiQPx.js?v=4973b764:35619
_getValue_unbound @ three.module-fIQxiQPx.js?v=4973b764:35596
saveOriginalState @ three.module-fIQxiQPx.js?v=4973b764:35311
_activateAction @ three.module-fIQxiQPx.js?v=4973b764:36607
play @ three.module-fIQxiQPx.js?v=4973b764:36100
loadModel @ VRMModel.vue:340
VRMModel.vue:340 THREE.PropertyBinding: No target node found for track: Normalized_J_Bip_R_Hand.quaternion.
(anonymous) @ rrweb-plugin-console-record.js:160
warn @ three.module-fIQxiQPx.js?v=4973b764:1593
bind @ three.module-fIQxiQPx.js?v=4973b764:35619
_getValue_unbound @ three.module-fIQxiQPx.js?v=4973b764:35596
saveOriginalState @ three.module-fIQxiQPx.js?v=4973b764:35311
_activateAction @ three.module-fIQxiQPx.js?v=4973b764:36607
play @ three.module-fIQxiQPx.js?v=4973b764:36100
loadModel @ VRMModel.vue:340
VRMModel.vue:340 THREE.PropertyBinding: No target node found for track: Normalized_J_Bip_L_UpperLeg.quaternion.
(anonymous) @ rrweb-plugin-console-record.js:160
warn @ three.module-fIQxiQPx.js?v=4973b764:1593
bind @ three.module-fIQxiQPx.js?v=4973b764:35619
_getValue_unbound @ three.module-fIQxiQPx.js?v=4973b764:35596
saveOriginalState @ three.module-fIQxiQPx.js?v=4973b764:35311
_activateAction @ three.module-fIQxiQPx.js?v=4973b764:36607
play @ three.module-fIQxiQPx.js?v=4973b764:36100
loadModel @ VRMModel.vue:340
VRMModel.vue:340 THREE.PropertyBinding: No target node found for track: Normalized_J_Bip_L_LowerLeg.quaternion.
(anonymous) @ rrweb-plugin-console-record.js:160
warn @ three.module-fIQxiQPx.js?v=4973b764:1593
bind @ three.module-fIQxiQPx.js?v=4973b764:35619
_getValue_unbound @ three.module-fIQxiQPx.js?v=4973b764:35596
saveOriginalState @ three.module-fIQxiQPx.js?v=4973b764:35311
_activateAction @ three.module-fIQxiQPx.js?v=4973b764:36607
play @ three.module-fIQxiQPx.js?v=4973b764:36100
loadModel @ VRMModel.vue:340
VRMModel.vue:340 THREE.PropertyBinding: No target node found for track: Normalized_J_Bip_L_Foot.quaternion.
(anonymous) @ rrweb-plugin-console-record.js:160
warn @ three.module-fIQxiQPx.js?v=4973b764:1593
bind @ three.module-fIQxiQPx.js?v=4973b764:35619
_getValue_unbound @ three.module-fIQxiQPx.js?v=4973b764:35596
saveOriginalState @ three.module-fIQxiQPx.js?v=4973b764:35311
_activateAction @ three.module-fIQxiQPx.js?v=4973b764:36607
play @ three.module-fIQxiQPx.js?v=4973b764:36100
loadModel @ VRMModel.vue:340
VRMModel.vue:340 THREE.PropertyBinding: No target node found for track: Normalized_J_Bip_L_ToeBase.quaternion.
(anonymous) @ rrweb-plugin-console-record.js:160
warn @ three.module-fIQxiQPx.js?v=4973b764:1593
bind @ three.module-fIQxiQPx.js?v=4973b764:35619
_getValue_unbound @ three.module-fIQxiQPx.js?v=4973b764:35596
saveOriginalState @ three.module-fIQxiQPx.js?v=4973b764:35311
_activateAction @ three.module-fIQxiQPx.js?v=4973b764:36607
play @ three.module-fIQxiQPx.js?v=4973b764:36100
loadModel @ VRMModel.vue:340
VRMModel.vue:340 THREE.PropertyBinding: No target node found for track: Normalized_J_Bip_R_UpperLeg.quaternion.
(anonymous) @ rrweb-plugin-console-record.js:160
warn @ three.module-fIQxiQPx.js?v=4973b764:1593
bind @ three.module-fIQxiQPx.js?v=4973b764:35619
_getValue_unbound @ three.module-fIQxiQPx.js?v=4973b764:35596
saveOriginalState @ three.module-fIQxiQPx.js?v=4973b764:35311
_activateAction @ three.module-fIQxiQPx.js?v=4973b764:36607
play @ three.module-fIQxiQPx.js?v=4973b764:36100
loadModel @ VRMModel.vue:340
VRMModel.vue:340 THREE.PropertyBinding: No target node found for track: Normalized_J_Bip_R_LowerLeg.quaternion.
(anonymous) @ rrweb-plugin-console-record.js:160
warn @ three.module-fIQxiQPx.js?v=4973b764:1593
bind @ three.module-fIQxiQPx.js?v=4973b764:35619
_getValue_unbound @ three.module-fIQxiQPx.js?v=4973b764:35596
saveOriginalState @ three.module-fIQxiQPx.js?v=4973b764:35311
_activateAction @ three.module-fIQxiQPx.js?v=4973b764:36607
play @ three.module-fIQxiQPx.js?v=4973b764:36100
loadModel @ VRMModel.vue:340
VRMModel.vue:340 THREE.PropertyBinding: No target node found for track: Normalized_J_Bip_R_Foot.quaternion.
(anonymous) @ rrweb-plugin-console-record.js:160
warn @ three.module-fIQxiQPx.js?v=4973b764:1593
bind @ three.module-fIQxiQPx.js?v=4973b764:35619
_getValue_unbound @ three.module-fIQxiQPx.js?v=4973b764:35596
saveOriginalState @ three.module-fIQxiQPx.js?v=4973b764:35311
_activateAction @ three.module-fIQxiQPx.js?v=4973b764:36607
play @ three.module-fIQxiQPx.js?v=4973b764:36100
loadModel @ VRMModel.vue:340
VRMModel.vue:340 THREE.PropertyBinding: No target node found for track: Normalized_J_Bip_R_ToeBase.quaternion.
```

### System Info

```Shell
System:
    OS: macOS 15.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 271.97 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 24.10.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /Users/neko/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 10.2.4 - /Users/neko/.volta/tools/image/node/21.6.2/bin/npm
    pnpm: 10.26.2 - /Users/neko/.volta/tools/image/node/21.6.2/bin/pnpm
    bun: 1.2.22 - /opt/homebrew/bin/bun
    Deno: 2.4.5 - /opt/homebrew/bin/deno
    Watchman: 2025.11.10.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 143.0.7499.192
    Firefox: 141.0
    Safari: 18.5
```

### Validations

- [x] Follow our [Code of Conduct](https://github.com/moeru-ai/airi/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guide](https://github.com/moeru-ai/airi/blob/main/.github/CONTRIBUTING.md).
- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [x] I am willing to submit a PR to fix this issue
- [x] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

### PR DESCRIPTION
**Pull request by shinohara-rin**
Removed broken dirLightReady dependency since TresDirectionalLight doesn't emit @ready event. 

Updated sceneReady to watch [controlsReady, modelLoaded, dirLightRef] instead. 

closes #893

### CODE REVIEW

File: packages/stage-ui-three/src/components/ThreeScene.vue [hunk 1]
```diff
@@ -295,6 +301,7 @@ defineExpose({
       :antialias="true"
       :width="width"
       :height="height"
+      :window-size="true"
```
Comment (shinohara-rin) [inline packages/stage-ui-three/src/components/ThreeScene.vue]: `TresCanvas: The canvas has no area, so nothing can be rendered. Set it manually on the parent element or use the prop windowSize.`
