### PR TITLE
fix(stage-ui) patch ModelSettings.validateFiles to support utf-8

### LINKED ISSUE #742: 含 unicode 的模型无法加载
### Describe the bug

Image
我在使用非纯英文的模型时无法正确加载，在移除-items_pinned_to_model.json文件后还必须把所有json文件内的中文改成英文才能正确加载，希望能修复这个问题，兼容更多的模型来源，我们将不甚感激！

### System Info

```Shell
windows11
```

### Validations

- [x] Follow our [Code of Conduct](https://github.com/moeru-ai/airi/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guide](https://github.com/moeru-ai/airi/blob/main/.github/CONTRIBUTING.md).
- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

### PR DESCRIPTION
**Pull request by shinohara-rin**
Closes #742

### CODE REVIEW

**Comment by shinohara-rin** [comment]
What's wrong with the autofix bot??

**Review by nekomeowww — APPROVED** [review]

File: packages/stage-ui/src/utils/live2d-zip-loader.ts [hunk 1]
```diff
@@ -2,7 +2,22 @@ import type { ModelSettings } from 'pixi-live2d-display/cubism4'
 
 import JSZip from 'jszip'
 
-import { Cubism4ModelSettings, ZipLoader } from 'pixi-live2d-display/cubism4'
+import { Cubism4ModelSettings, ModelSettings as ModelSettingsClass, ZipLoader } from 'pixi-live2d-display/cubism4'
+
+// NOTICE: Patch to handle UTF-8 encoded file paths in model settings
```
Comment (nekomeowww) [inline packages/stage-ui/src/utils/live2d-zip-loader.ts:8]:
```suggestion
// TODO: this is a bit hacky, do we have other choice?
// NOTICE: Patch to handle UTF-8 encoded file paths in model settings
```
